apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-pvc
  namespace: dev

spec:
  storageClassName: ""

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 500Mi