apiVersion: apps/v1
kind: Deployment

metadata:
  name: k8s-web

spec:
  replicas: 1

  selector:
    matchLabels:
      app: k8s-web

  template:
    metadata:
      labels:
        app: k8s-web

    spec:
      containers:
        - name: k8s-web
          image: aldocloud/devops-kubernetes-project:v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80