replicaCount: 5

image:
  tag: v3
  pullPolicy: IfNotPresent

config:
  appEnv: production

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  hosts:
    - host: devops.local
      paths:
        - path: /
          pathType: Prefix