[local]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[management]
ansible-host ansible_host=47.128.245.147 ansible_user=ubuntu ansible_ssh_private_key_file=/home/aldo0/.ssh/ansible-ec2 ansible_python_interpreter=/usr/bin/python3
