apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-app.fullname" . }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "devops-app.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "devops-app.selectorLabels" . | nindent 8 }}

    spec:
      serviceAccountName: {{ include "devops-app.fullname" . }}

      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- if .Values.topologySpreadConstraints.enabled }}
      topologySpreadConstraints:
        - maxSkew: {{ .Values.topologySpreadConstraints.maxSkew }}
          topologyKey: {{ .Values.topologySpreadConstraints.topologyKey }}
          whenUnsatisfiable: {{ .Values.topologySpreadConstraints.whenUnsatisfiable }}
          labelSelector:
            matchLabels:
              {{- include "devops-app.selectorLabels" . | nindent 14 }}
      {{- end }}

      containers:
        - name: devops-app

          {{- if .Values.lifecycle.preStop.enabled }}
          lifecycle:
            preStop:
              exec:
                command:
                  {{- toYaml .Values.lifecycle.preStop.command | nindent 18 }}
          {{- end }}

          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

          envFrom:
            - configMapRef:
                name: {{ include "devops-app.fullname" . }}-config
            - secretRef:
                name: {{ .Values.secret.existingSecret }}

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 3

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
