apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-app.fullname" . }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}

spec:
  {{- if not .Values.autoscaling.enabled }}
    replicas: {{ .Values.replicaCount }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "devops-app.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "devops-app.selectorLabels" . | nindent 8 }}

    spec:
      serviceAccountName: {{ include "devops-app.fullname" . }}

      containers:
        - name: devops-app

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 3000

          envFrom:
            - configMapRef:
                name: {{ include "devops-app.fullname" . }}-config
            - secretRef:
                name: {{ include "devops-app.fullname" . }}-secret

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 3

          resources:
            {{- toYaml .Values.resources | nindent 12 }}