{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-app.fullname" . }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secret.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  APP_SECRET: {{ .Values.secret.appSecret | quote }}
{{- end }}
