apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: {{ include "devops-app.fullname" . }}
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "devops-app.name" . }}

  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}

  endpoints:
    - port: http
      path: /metrics
      interval: 15s