name: Docker Build Scan and Push

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/docker.yml"

  workflow_dispatch:

permissions:
  contents: write

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/devops-kubernetes-project

jobs:
  container:
    name: Build Scan Push and Update GitOps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          load: true
          push: false
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: table
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "HIGH,CRITICAL"

      - name: Push Git SHA Image
        run: docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Push Latest Image
        run: docker push ${{ env.IMAGE_NAME }}:latest

      - name: Update Helm Image Tag
        run: |
          sed -i "s/^  tag: .*/  tag: ${GITHUB_SHA}/" helm/devops-app/values.yaml

      - name: Verify Updated Image Tag
        run: |
          grep -A3 "^image:" helm/devops-app/values.yaml

      - name: Commit GitOps Image Update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add helm/devops-app/values.yaml

          if git diff --cached --quiet; then
            echo "No image tag changes detected."
            exit 0
          fi

          git commit -m "gitops: deploy image ${GITHUB_SHA}"
          git push origin main